using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public partial class ConnectingHud : Control
{
    public Button ReconnectButton => Button;
        
    public void ShowMessage(string message)
    {
        Message.Show(message);
    }

    public void HideMessage()
    {
        Message.Hide();
    }
}