using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public partial class MessageControl : Control
{
    protected override void EnteredTree()
    {
        base.EnteredTree();

        Visible = false;
    }

    public void Show(string text)
    {
        Label.Text = text;
        Visible = true;
    }

    public void Hide()
    {
        Label.Text = string.Empty;
        Visible = false;
    }
}